### ISSUE TITLE
commit eclipse settings to repo

### ISSUE THREAD

**Issue by mschn** [mschn/wissl#25]
Some eclipse project settings are pretty much needed.
Example:
- javascript formatter settings
- java formatter settings
- tomcat launch configuration
- ignore validation for javascript minified sources

**Comment by atrovato** [comment]
Eclipse doesn't open the project as Web project.
.settings/\* file missing :
- org.eclipse.wst.common.component ?
- org.eclipse.wst.common.project.facet.core.xml ?

**Comment by mschn** [comment]
I committed the whole content of my `.settings`.
Right now on my workspace, the project does not register as 'web project' but 'java project'.

I don't know how to convert the project to a 'web project', but I don't think it really matters.
You can have the project launch as a web application by just adding a new external module:
- double click on you tomcat server in the Servers view in eclipse
- click the 'modules' tab
- click 'Add external web module'
- use `/home/mschnoor/wissl.git/WebContent` as document base, `/` as Path
- edit the launch configuration of your tomcat so that it has `-Dwsl.config=/home/mschnoor/wissl.git/config.ini` as VM argument
- start tomcat

**Comment by atrovato** [comment]
If I configure my env with your information, I have a `java.lang.ClassNotFoundException: fr.msch.wissl.server.Bootstrap`.

You should have create a 'web project' on start, now there is to much 'external' configuration to improve to run the project.

**Comment by mschn** [comment]
You get this error because you did not compile. You need to run the ant build.

It's simple enough for me, I do the setup once and never think about it again.
Ideally you should not commit IDE configuration to the repository: not everyone use Eclipse and the ant script is enough to build and run in 2 commands.
